# Generated by Django 6.0.5 on 2026-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('received', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible in store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
